name: Trigger Fork Repo Action

on:
  push:
    branches:
      - main

jobs:
  trigger-fork:
    if: github.repository_owner == 'subject-test-22'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/inji0212/CICD_copied/dispatches" \
          -d '{"event_type": "main_updated"}'
